In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [2]:
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)
print("Data type:", arr.dtype)

Shape: (5,)
Dimensions: 1
Size: 5
Data type: int64


In [3]:
print(arr[0])      # First element
print(arr[2])      # Third element
print(arr[1:4])    # Elements from index 1 to 3
print(arr[:3])     # First three elements
print(arr[-2:])    # Last two elements

1
3
[2 3 4]
[1 2 3]
[4 5]


In [4]:
print(arr + 10)
print(arr * 2)
print(arr ** 2)

[11 12 13 14 15]
[ 2  4  6  8 10]
[ 1  4  9 16 25]


In [5]:
print("Mean:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))
print("Sum:", np.sum(arr))

Mean: 3.0
Maximum: 5
Minimum: 1
Sum: 15


In [8]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(matrix)

[[1 2 3]
 [4 5 6]]


In [9]:
numbers = np.arange(12)

print(numbers)

print(numbers.reshape(3,4))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
random_numbers = np.random.rand(2,4)

print(random_numbers)

[[0.26099413 0.04820994 0.9405699  0.66837486]
 [0.91551583 0.54158724 0.09019655 0.75640204]]


In [12]:
arr = np.array([2,5,8,1,9])

print(arr[arr > 5])

[8 9]


In [1]:
#Panda Basics

In [2]:
import pandas as pd

In [3]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [20, 21, 22, 23],
    "Marks": [85, 90, 78, 88]
}

df = pd.DataFrame(data)

df

,Name,Age,Marks
0,Alice,20,85
1,Bob,21,90
2,Charlie,22,78
3,David,23,88


In [4]:
print(df)

df.head()

df.tail()

      Name  Age  Marks
0    Alice   20     85
1      Bob   21     90
2  Charlie   22     78
3    David   23     88


,Name,Age,Marks
0,Alice,20,85
1,Bob,21,90
2,Charlie,22,78
3,David,23,88


In [5]:
df[["Name", "Marks"]]

,Name,Marks
0,Alice,85
1,Bob,90
2,Charlie,78
3,David,88


In [7]:
df[df["Marks"] > 80]
df[df["Age"] > 21]

,Name,Age,Marks
2,Charlie,22,78
3,David,23,88


In [8]:
print(df["Marks"].mean())
print(df["Marks"].max())
print(df["Marks"].min())

85.25
90
78


In [9]:
students = pd.DataFrame({
    "Department": ["CSE","CSE","ECE","ECE","MECH"],
    "Marks":[80,90,75,95,85]
})

students

,Department,Marks
0,CSE,80
1,CSE,90
2,ECE,75
3,ECE,95
4,MECH,85


In [10]:
students.groupby("Department")["Marks"].mean()

Department
CSE     85.0
ECE     85.0
MECH    85.0
Name: Marks, dtype: float64

In [11]:
df = pd.read_csv("students.csv")

df

,Name,Age,Marks
0,Alice,20,85
1,Bob,21,90
2,Charlie,22,78
3,David,23,88
4,Eva,20,95


In [12]:
df.head()

df.describe()

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str  
 1   Age     5 non-null      int64
 2   Marks   5 non-null      int64
dtypes: int64(2), str(1)
memory usage: 252.0 bytes


In [13]:
df[df["Marks"] > 85]

,Name,Age,Marks
1,Bob,21,90
3,David,23,88
4,Eva,20,95
